### ISSUE TITLE
How to update less preferences with a lesskey file on OSX

### ISSUE THREAD

**Issue by adrianbrink** [bunnyfly/dotfiles#2]
Awesome dotfiles. The first properly organised version for colemak and vim users on OSX.

The only thing that I can't figure out is: How do I get less to pick up the .lesskey settings?

On Ubuntu you can just run 'lesskey ~/.lesskey' and less will use the new preferences. On OSX lesskey doesn't exist (or I don't know the path to it) and settings the LESSKEY env variable doesn't help either.

Question is: How did you  do it?

**Comment by bunnyfly** [comment]
Thanks :) glad they're helpful!

OSX's default less is by configured without the lesskey option (which if enough people wrote them about it, they could conceivably change...not sure why they do that). You can install your own though. Verify the [most recent version of less's URL](http://www.greenwoodsoftware.com/less/download.html) and do something like:

wget http://www.greenwoodsoftware.com/less/less-481.zip
unzip less-481.zip
cd less-481
./configure && make install

This installs it to /usr/local/bin...you may need to change your PATH order or replace /usr/bin/less with /usr/local/bin/less or a link to it. No need to use full paths, if you have that right, but either way, test it out with:

/usr/local/bin/lesskey ~/.lesskey
/usr/local/bin/less ~/.vimrc

**Comment by bunnyfly** [comment]
Added these instructions to https://github.com/bunnyfly/dotfiles/blob/master/README.md

Lemme know if this gives you any trouble, adrianbrink!
